package:
  name: chemview
  version: git

source:
  git_url: git@github.com:gabrielelanaro/chemview.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipython-notebook
    - numpy
    - numba

test:
  imports:
    - chemview

about:
  home: http://chemview.rtfd.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: WebGL Molecular Viewer for IPython notebook.
