package:
  name: chemview
  version: !!str 0.1.2

source:
  git_url: git@github.com:gabrielelanaro/chemview.git
#  git_tag: v0.1.1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute
    - ipython-notebook
    - numpy
    - numba

test:
  imports:
    - chemview

about:
  home: http://chemview.rtfd.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: WebGL Molecular Viewer for IPython notebook.
